name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 使用 Node.js 18

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js app
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: wuhao126
          password: wuhao126...

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wuhao126/api_vue_show:0.0.1
          file: Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 101.126.87.57
          username: root
          password: wuhao126...
          script: |
            docker stop api_vue || true
            docker rm api_vue || true
            docker rmi wuhao126/api_vue_show:0.0.1 || true
            docker pull wuhao126/api_vue_show:0.0.1
            docker run -d --name api_vue -p 80:80 wuhao126/api_vue_show:0.0.1
